#+TITLE: MouseReachRotaryRig
#+AUTHOR: Peter Polidoro
#+EMAIL: peter@polidoro.io

* Mouse Reach Rotary Rig

** Repositories

*** Hardware

[[https://github.com/janelia-kicad/mouse_reach_controller][Mouse Reach Controller]]

[[https://github.com/janelia-kicad/stepper_driver][Stepper Driver]]

*** Firmware

[[https://github.com/janelia-arduino/MouseReachRotaryController][Mouse Reach Rotary Controller]]

** Assembly

*** Stepper Motor

[[./datasheets/SY42STH38-1684A.pdf][SY42STH38-1684A]]

1) Trim motor wires to 40mm.
2) Strip 6mm of insulation from each motor wire.
3) Crimp ferrule connector onto each motor wire.
4) Remove 4 screws from the back of the motor.

*** Stepper Driver

[[./datasheets/TMC2209_SilentStepStick_datasheet_Rev1.20.pdf][TMC2209 SilentStepStick]]

[[https://github.com/janelia-kicad/stepper_driver][Janelia Stepper Driver]]

1) Solder the 3 jumper pads together connecting the PDN and UART pins on the
   TMC2209 SilentStepStick.
2) Solder the 2 8-pin headers onto the TMC2209 SilentStepStick.
3) Insert TMC2209 SilentStepStick into the stepper_driver board.
4) Use a sticky thermal pad to attach a heat sink onto the TMC2209
   SilentStepStick.
5) Strip 6mm of insulation from each wire on the power jack cable.
6) Crimp ferrule connector onto each wire on the power jack cable.
7) Attach marked power jack cable wire into the positive pin of the
   stepper_driver board power connector.
8) Attach the second power jack cable wire into the ground pin of the
   stepper_driver board power connector.

*** Motor and Driver Assembly

1) Attach the stepper_driver board to the back of the motor using 4 spacers and
   4 screws with the 4-pin connector oriented closest to the motor wires.
2) Attach motor wires to the 4-pin connector on the stepper_driver according to
   the wiring diagram.
3) Attach ribbon cable to the stepper_driver board oriented so the ribbon cable
   points towards the motor wires.

*** Mouse Reach Controller



